Models/Book.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVCLibrary.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int LibraryId { get; set; }
        public Library Library { get; set; }
    }

}

Models/Libray.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace MVCLibrary.Models
{
    public class Library
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public virtual ICollection<Book> Books { get; set; } = new List<Book>();

    }

}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MVCLibrary.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCLibrary.Models;

namespace MVCLibrary.Controllers
{
    public class LibraryController : Controller
    {
        private readonly LibraryContext _db;
        public LibraryController(LibraryContext libraryContext)
        {
            _db = libraryContext;
        }

        public IActionResult Index()
        {
            var libraries = _db.Libraries.ToList();
            return View(libraries);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Library library)
        {
            _db.Libraries.Add(library);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet("/library/{libraryId}/books")]
        public IActionResult AddBook()
        {
            return View();
        }

        [HttpPost("/library/{libraryId}/books")]
        public IActionResult AddBook(int libraryId, Book book)
        {
            var library = GetLibrary(libraryId);

            if (library == null)
            {
                return NotFound("This library does not exists");
            }
            book.LibraryId = libraryId;
            _db.Books.Add(book);
            _db.SaveChanges();
            return RedirectToAction("Details", new { @id = libraryId });
        }

        public IActionResult Details(int id)
        {
            var library = _db.Libraries.Include(x => x.Books).FirstOrDefault(x => x.Id == id);
            return View(library);
        }

        public IActionResult RemoveBook(int libraryId, int bookId)
        {
            var b = _db.Books.Find(bookId);
            _db.Books.Remove(b);
            _db.SaveChanges();
            return RedirectToAction("Details", new { @id = libraryId });
        }

        private Library GetLibrary(int id)
        {
            return _db.Libraries.Find(id);
        }
    }
}

Views/Home/About.cshtml
@{ ViewData["Title"] = "About"; }
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{ ViewData["Title"] = "Contact"; }
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
	One Microsoft Way<br /> Redmond, WA 98052-6399<br />
	<abbr title="Phone">P:</abbr> 425.555.0100
</address>

<address>
	<strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
	<strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home Page"; }

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
		<li data-target="#myCarousel" data-slide-to="3"></li>
	</ol>
	<div class="carousel-inner" role="listbox">
		<div class="item active">
			<img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
			<div class="carousel-caption" role="option">
				<p>
					Learn how to build ASP.NET apps that can run anywhere.
					<a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
				</p>
			</div>
		</div>
		<div class="item">
			<img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
			<div class="carousel-caption" role="option">
				<p>
					There are powerful new features in Visual Studio for building modern web apps.
					<a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
				</p>
			</div>
		</div>
		<div class="item">
			<img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
			<div class="carousel-caption" role="option">
				<p>
					Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
					<a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
				</p>
			</div>
		</div>
		<div class="item">
			<img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
			<div class="carousel-caption" role="option">
				<p>
					Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
					<a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
				</p>
			</div>
		</div>
	</div>
	<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>
<div class="row">
	<div class="col-md-3">
		<h2>Application uses</h2>
		<ul>
			<li>Sample pages using ASP.NET Core MVC</li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a>				for managing client-side libraries</li>
			<li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
		</ul>
	</div>
	<div class="col-md-3">
		<h2>How to</h2>
		<ul>
			<li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkID=699562">Add an appsetting in config and access it in app.</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
		</ul>
	</div>
	<div class="col-md-3">
		<h2>Overview</h2>
		<ul>
			<li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
		</ul>
	</div>
	<div class="col-md-3">
		<h2>Run & Deploy</h2>
		<ul>
			<li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
			<li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
		</ul>
	</div>
</div>

Views/Library/AddBook.cshtml
@model MVCLibrary.Models.Book
@{ ViewBag.Title = "Add Book"; }

<h2>@ViewData["Title"]</h2>

<form asp-controller="Library" asp-action="AddBook" method="post" class="form-horizontal" role="form">
	<div class="form-horizontal">
		<div asp-validation-summary="All" class="text-danger"></div>
		<div class="form-group">
			<label asp-for="@Model.Title" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="@Model.Title" class="form-control" />
				<span asp-validation-for="@Model.Title" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="@Model.Author" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="@Model.Author" class="form-control" />
				<span asp-validation-for="@Model.Author" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
</form>

Views/Library/Create.cshtml
@model MVCLibrary.Models.Library 
@{ ViewBag.Title = "Add Library"; }

<h2>@ViewData["Title"]</h2>

<form asp-controller="Library" asp-action="Create" method="post" class="form-horizontal" role="form">
	<div class="form-horizontal">
		<div asp-validation-summary="All" class="text-danger"></div>
		<div class="form-group">
			<label asp-for="@Model.Name" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="@Model.Name" class="form-control" />
				<span asp-validation-for="@Model.Name" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="@Model.Address" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="@Model.Address" class="form-control" />
				<span asp-validation-for="@Model.Address" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
</form>

Views/Library/Details.cshtml
@model MVCLibrary.Models.Library 
@{ ViewBag.Title = Model.Name; }

<h2>@ViewBag.Title</h2>
<h5>@Model.Address</h5>

<h3>Total Books: @Model.Books.Count</h3>

<a asp-controller="Library" asp-action="AddBook" asp-route-libraryId="@Model.Id">Add Book</a>

<table class="table">
	<tr>
		<th>Title</th>
		<th>Author</th>
		<th>Actions</th>
	</tr>
	@foreach (var book in Model.Books){
	<tr>
		<td>@book.Title</td>
		<td>@book.Author</td>
		<td>
			<a asp-controller="Library" asp-action="BookDetails" asp-route-libraryId="@Model.Id" asp-route-bookId="@book.Id">Details</a>
			<a asp-controller="Library" asp-action="RemoveBook" asp-route-libraryId="@Model.Id" asp-route-bookId="@book.Id">Trash</a>
		</td>
	</tr>
	}
</table>

Views/Library/Getbook.cshtml
@model MVCLibrary.Models.Book
@{ ViewBag.Title = Model.Title; }

<a asp-controller="Library" asp-action="Index">Back</a>

<h2>@ViewData["Title"]</h2>
<h5>@Model.Author</h5>

Views/Library/Index.cshtml
@model List<MVCLibrary.Models.Library>

	@{ ViewBag.Title = "The Great Libraries";}

	<h2>@ViewBag.Title</h2>

	<h3>@Model.Count</h3>


	<a asp-controller="Library" asp-action="Create">Add Library</a>


	<table class="table">
		<tr>
			<th>Id</th>
			<th>Url</th>
			<th>Actions</th>
		</tr>
		@foreach (var library in Model){
		<tr>
			<td>@library.Name</td>
			<td>@library.Address</td>
			<td>
				<a asp-controller="Library" asp-action="Details" asp-route-id="@library.Id">Details</a>
			</td>
		</tr>
		}
	</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - MVCLibrary</title>

	<environment names="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment names="Staging,Production">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css" asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				<a asp-controller="Home" asp-action="Index" class="navbar-brand">MVCLibrary</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-controller="Home" asp-action="Index">Home</a></li>
					<li><a asp-controller="Home" asp-action="About">About</a></li>
					<li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2016 - MVCLibrary</p>
		</footer>
	</div>

	<environment names="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment names="Staging,Production">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js" asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
			asp-fallback-test="window.jQuery">
        </script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js" asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
			asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("scripts", required: false)
</body>

</html>